runtime: nodejs
env: flex

service: api

env_variables:
  TZ: utc

  SQL_USER: YOUR_SQL_USER
  SQL_PASSWORD: YOUR_SQL_PASSWORD
  SQL_DATABASE: YOUR_SQL_DATABASE

  INSTANCE_CONNECTION_NAME: YOUR_INSTANCE_CONNECTION_NAME

  CORS_DOMAIN: YOUR_CORS_DOMAIN

  PRIVATE_API_KEY: YOUR_PRIVATE_API_KEY

beta_settings:
  cloud_sql_instances: YOUR_INSTANCE_CONNECTION_NAME

manual_scaling:
  instances: 1

#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 10
#  cool_down_period_sec: 120 # default value
#  cpu_utilization:
#    target_utilization: 0.5
